# Prefer the project venv's interpreter if it exists, otherwise fall back
# to whatever `python3` is on PATH (e.g. inside CI or a container where
# dependencies are already installed into the active environment).
PYTHON := $(shell [ -x .venv/bin/python ] && echo .venv/bin/python || echo python3)

.PHONY: help install lint test test-cov run worker up down logs migrate migration clean

help:
	@echo "Common targets:"
	@echo "  install    Install the package and dev dependencies into .venv"
	@echo "  lint       Run ruff"
	@echo "  test       Run the pytest suite (SQLite in-memory, no Docker needed)"
	@echo "  test-cov   Run pytest with a coverage report"
	@echo "  run        Run the API locally with uvicorn --reload"
	@echo "  worker     Run the worker process locally"
	@echo "  migrate    Apply Alembic migrations against DATABASE_URL"
	@echo "  migration  Create a new autogenerated Alembic revision (m=\"message\")"
	@echo "  up         Start the full stack (db + migrate + api + worker) via Docker Compose"
	@echo "  down       Stop and remove the Docker Compose stack"
	@echo "  logs       Tail logs from the Docker Compose stack"
	@echo "  clean      Remove caches and build artifacts"

install:
	python3 -m venv .venv
	.venv/bin/pip install --upgrade pip
	.venv/bin/pip install -e ".[dev]"

lint:
	$(PYTHON) -m ruff check .

test:
	$(PYTHON) -m pytest

test-cov:
	$(PYTHON) -m pytest --cov=app --cov-report=term-missing

run:
	$(PYTHON) -m uvicorn app.main:app --reload --host 0.0.0.0 --port 8000

worker:
	$(PYTHON) -m app.worker

migrate:
	$(PYTHON) -m alembic upgrade head

migration:
	$(PYTHON) -m alembic revision --autogenerate -m "$(m)"

up:
	docker compose up --build -d

down:
	docker compose down -v

logs:
	docker compose logs -f

clean:
	find . -type d -name "__pycache__" -exec rm -rf {} +
	rm -rf .pytest_cache .ruff_cache .coverage htmlcov
